# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3891a6879de8be5f514133562c083e16378ce4ca771d29fc5452ff0ed68be993f71203e1cf62526e7e0e0ad9921c3167b529e0b6ad1ce5a343985f97fbb76b74

test:
  secret_key_base: 25a11ba4afeb5165214a9df5f87b7c91bc295d26b891ef03e54bd9cd5dbc78de2fb47b1facd51fd3374f20047bc55b0a27ce2a3dee76a281a05ef5a00b79e90a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
